name: Ejecución Tests con Selenium

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Dar permisos a gradlew
      uses: gradle/actions/setup-gradle@v4

    #build completo
    - name: Build del proyecto
      run: chmod +x ./gradlew
    - name: Build del proyecto
      run: ./gradlew build

    # Usando el tag:
    - name: Ejecutar pruebas por tag
      run: ./gradlew clean test -Dcucumber.filter.tags=@FlujoCompleto

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
